PROVIDER = "virtualbox"
NETWORK = "private_network"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider PROVIDER do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.define "acroueS" do |control|
    control.vm.hostname = "acroueS"
    control.vm.network NETWORK, ip: "192.168.56.110"

    control.vm.provider PROVIDER do |v|
      v.customize ["modifyvm", :id, "--name", "acroueS"]
    end

    control.vm.provision "shell", path: "./scripts/init_server.sh"
  end

end
